# Generated by Django 5.2.7 on 2025-11-08 02:57

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paying_customer', models.BooleanField(default=False)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('timestamp_file', models.FileField(blank=True, null=True, upload_to=core.models.timestamp_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100)),
                ('phrase_status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phrases')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase_Meanings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=500)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phrases')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedAudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_audio', models.BooleanField(default=False)),
                ('has_whisper_result', models.BooleanField(default=False)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.upload_audio_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('whisper_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('whisper_file', models.FileField(blank=True, null=True, upload_to=core.models.upload_whisper_result)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=core.models.upload_text_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_key', models.CharField(max_length=50)),
                ('word_status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.words')),
            ],
        ),
        migrations.CreateModel(
            name='Word_Meanings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=500)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.words')),
            ],
        ),
    ]
