# Generated by Django 5.2.7 on 2026-02-28 02:50

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('last_open_at', models.DateTimeField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('topcie', models.CharField(blank=True, max_length=100, null=True)),
                ('course_img_file', models.FileField(blank=True, null=True, upload_to=core.models.upload_course_file)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_goal', models.IntegerField(default=120)),
                ('is_paying_customer', models.BooleanField(default=False)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_to_learn_at', models.DateTimeField(blank=True, null=True)),
                ('phrase', models.CharField(max_length=100)),
                ('phrase_status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phrases')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase_Meanings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=500)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phrases')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_to_learn_at', models.DateTimeField(blank=True, null=True)),
                ('word_key', models.CharField(max_length=50)),
                ('word_status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.words')),
            ],
        ),
        migrations.CreateModel(
            name='Word_Meanings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=500)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.words')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_open_at', models.DateTimeField(blank=True, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_start_time', models.FloatField(blank=True, null=True)),
                ('youtube_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('text_file', models.FileField(upload_to=core.models.upload_lesson_file)),
                ('lesson_img_file', models.FileField(blank=True, null=True, upload_to=core.models.upload_lesson_file)),
                ('has_audio', models.BooleanField(default=False)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=core.models.upload_lesson_file)),
                ('has_timestamp', models.BooleanField(default=False)),
                ('whisper_file', models.FileField(blank=True, null=True, upload_to=core.models.upload_lesson_file)),
                ('timestamp_file', models.FileField(blank=True, null=True, upload_to=core.models.upload_lesson_file)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'lesson_name'), name='uniq_course_lesson_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='phrases',
            constraint=models.UniqueConstraint(fields=('user', 'phrase'), name='uniq_phrase_user_phrase'),
        ),
        migrations.AddConstraint(
            model_name='phrase_tags',
            constraint=models.UniqueConstraint(fields=('phrase', 'tag'), name='uniq_phrase_tag'),
        ),
        migrations.AddConstraint(
            model_name='phrase_meanings',
            constraint=models.UniqueConstraint(fields=('phrase', 'meaning'), name='uniq_phrase_meaning'),
        ),
        migrations.AddConstraint(
            model_name='words',
            constraint=models.UniqueConstraint(fields=('user', 'word_key'), name='uniqu_words_word_word_key'),
        ),
        migrations.AddConstraint(
            model_name='word_tags',
            constraint=models.UniqueConstraint(fields=('word', 'tag'), name='uniq_word_tag'),
        ),
        migrations.AddConstraint(
            model_name='word_meanings',
            constraint=models.UniqueConstraint(fields=('word', 'meaning'), name='uniq_word_word_meaning'),
        ),
    ]
