# Generated by Django 5.2.7 on 2026-01-12 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='phrase_meanings',
            constraint=models.UniqueConstraint(fields=('phrase', 'meaning'), name='uniq_phrase_meaning'),
        ),
        migrations.AddConstraint(
            model_name='phrase_tags',
            constraint=models.UniqueConstraint(fields=('phrase', 'tag'), name='uniq_phrase_tag'),
        ),
        migrations.AddConstraint(
            model_name='phrases',
            constraint=models.UniqueConstraint(fields=('user', 'phrase'), name='uniq_phrase_user_phrase'),
        ),
        migrations.AddConstraint(
            model_name='word_meanings',
            constraint=models.UniqueConstraint(fields=('word', 'meaning'), name='uniq_word_word_meaning'),
        ),
        migrations.AddConstraint(
            model_name='word_tags',
            constraint=models.UniqueConstraint(fields=('word', 'tag'), name='uniq_word_tag'),
        ),
        migrations.AddConstraint(
            model_name='words',
            constraint=models.UniqueConstraint(fields=('user', 'word_key'), name='uniqu_words_word_word_key'),
        ),
    ]
